bugtracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views

app_name = "main"
urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('<int:bug_id>', views.detail, name='detail'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('login/register/',views.register_view, name='register'),
    path('newbug/', views.new_bug, name='newbug'),
]

main/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

severity_choices = (
    ('low', 'Low'),
    ('medium', 'Medium'),
    ('high', 'High'),
    ('critical', 'Critical'),
)

status = (
    ('assigned', 'Assigned'),
    ('unassigned', 'UnAssigned'),
    ('waiting_for_response', 'Waiting for Response'),
    ('dropped', 'Dropped'),
)
class Bug(models.Model):
    bug_category = models.CharField(max_length=200)
    bug_summary = models.TextField(max_length=200)
    bug_severity = models.CharField(max_length=8, choices=severity_choices, default='low')
    bug_desc = models.TextField(max_length=500)
    bug_status = models.CharField(max_length=20, choices=status, default='unassigned')
    date_reported = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.bug_summary



main/forms.py
from django import forms
from .models import Bug

class bug_creation_form(forms.ModelForm):
    class Meta:
        model=Bug
        fields = "__all__"

class login_form(forms.Form):
    user_name = forms.CharField(max_length=200)
    password = forms.CharField(widget=forms.PasswordInput())

class register_form(forms.Form):
    first_name=forms.CharField(max_length=30)
    last_name=forms.CharField(max_length=30)
    user_name=forms.CharField(max_length=50)
    email_id=forms.EmailField(max_length=200)
    password=forms.CharField(widget=forms.PasswordInput())
    confirm_password=forms.CharField(widget=forms.PasswordInput())

main/views.py
from django.shortcuts import render, get_object_or_404

from django.http import HttpResponse
from .models import Bug
from .forms import login_form, bug_creation_form, register_form

# Create your views here.

def home_page(request):
    recent_bug_reports = Bug.objects.order_by('-date_reported')[:20]
    context = {
        'recent_bug_reports': recent_bug_reports,
    }
    return render(request, 'main/home_page.html', context)

# def sort_by_id(request):
#     recent_bug_reports = Bug.objects.order_by('-id')[:20]
#     context = {
#         'recent_bug_reports': recent_bug_reports,
#     }
#     return render(request, 'main/home_page_by_id.html', context)

def detail(request, bug_id):
    bug=get_object_or_404(Bug, pk=bug_id)
    return render(request, 'main/detail.html', {'bug':bug})

def login_view(request):
    return render(request, 'main/login.html', {'form':login_form})

# def register_view(request):
#     print(request.POST)
#     if(request.password==request.confirm_Password):
#         return render(request, 'main/register.html', {'form':register_form})           # work with this later
#     else:
#         return render(request, 'main/pass_no_match.html')

def register_view(request):
    return render(request, 'main/register.html', {'form':register_form})


def new_bug(request):
    form = bug_creation_form(request.POST or None)
    if form.is_valid():
        form.save()
    return render(request, 'main/user_bug_creation.html', {'form':form})

# def new_bug(request):
#     return render(request, 'main/user_bug_creation.html')

# def welcome_view(request,username):
#     username=request.GET(username)
#     return render(request, 'main/welcome.html', {'user':username})


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     #output = ', '.join([q.question_text for q in latest_question_list])
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return render(request, 'polls/index.html', context)

main/templates/main/admin_bug_edit.html
Summary: {{bug.bug_summary}}<br \><br \><br \>
Description: {{bug.bug_desc}}<br \><br \><br \>
Category: {{bug.bug_category}}<br \><br \><br \>
Severity: {{bug.bug_severity}}<br \><br \><br \>
Status: <select name="status">
    <option value="unassigned">Unassigned</option>
    <option value="assigned">Assigned</option>
    <option value="waiting_for_response">Waitlist</option>
    <option value="dropped">Dropped</option>
</select>

<!-- Status: <input type="radio" name="assigned"> Assigned  <input type="radio" name="waiting_for_response"> Waiting for Response  <input type="radio" name="dropped"> Package out of Date -->

main/templates/main/detail.html
<h1>{{ bug.bug_summary }}</h1>

    <p>Bug ID: {{ bug.id }}</p>
    <p>Bug Description: {{ bug.bug_desc }}</p>
    <p>Bug Category: {{ bug.bug_category }}</p>
    <p>Severity: {{ bug.bug_severity }}</p>
    <p>Status: {{ bug.bug_status }}</p>
    <p>Date Reported: {{ bug.date_reported }}</p>

main/templates/main/home_page.html

<a href="{% url 'main:login' %}"><button>Login</button></a>
<a href="{% url 'main:newbug' %}"><button>Create Bug</button></a>

{% if recent_bug_reports %}
<table border="1px solid-black" border-collapse: collapse;>
    <th><a style="text-decoration:none" href="">Bug ID</a></th>
    <th><a style="text-decoration:none" href="">Category</a></th>
    <th><a style="text-decoration:none" href="">Summary</a></th>
    <th><a style="text-decoration:none" href="">Severity</a></th>
    <th><a style="text-decoration:none" href="">Created On</a></th>
    <th><a style="text-decoration:none" href="">Status</a></th>
    {% for bug in recent_bug_reports %}
    <tr>
    <td><a style="text-decoration:none" href="{% url 'main:detail' bug.id %}">{{ bug.id }}</a></td>
    <td><a style="text-decoration:none" href="{% url 'main:detail' bug.id %}">{{ bug.bug_category }}</a></td>
    <td><a style="text-decoration:none" href="{% url 'main:detail' bug.id %}">{{ bug.bug_summary }}</a></td>
    <td><a style="text-decoration:none" href="{% url 'main:detail' bug.id %}">{{ bug.bug_severity }}</a></td>
    <td><a style="text-decoration:none" href="{% url 'main:detail' bug.id %}">{{ bug.date_reported }}</a></td>
    <td><a style="text-decoration:none" href="{% url 'main:detail' bug.id %}">{{ bug.bug_status }}</a></td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>No Bugs were reported yet</p>
{% endif %}

main/templates/main/home_page_al.html
{% if recent_bug_reports %}
<table border="1">
    <th>Bug ID</th>
    <th>Category</th>
    <th>Summary</th>
    <th>Severity</th>
    <th>Created On</th>
    <th>Status</th>
    {% for bug in recent_bug_reports %}
    <tr>
    <td><a href="{% url 'main:detail' bug.id %}">{{ bug.id }}</a></td>
    <td><a href="{% url 'main:detail' bug.id %}">{{ bug.bug_category }}</a></td>
    <td><a href="{% url 'main:detail' bug.id %}">{{ bug.bug_summary }}</a></td>
    <td><a href="{% url 'main:detail' bug.id %}">{{ bug.bug_severity }}</a></td>
    <td><a href="{% url 'main:detail' bug.id %}">{{ bug.date_reported }}</a></td>
    <td><a href="{% url 'main:detail' bug.id %}">{{ bug.bug_status }}</a></td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>No Bugs were reported yet</p>
{% endif %}

<a href="{% url 'main:newbug' %}"><button>Create Bug</button>></a>

main/templates/main/home_page_by_id.html

<a href="{% url 'main:login' %}"><button>Login</button></a>
<a href="{% url 'main:newbug' %}"><button>Create Bug</button></a>

{% if recent_bug_reports %}
<table border="1px solid-black" border-collapse: collapse;>
    <th><a style="text-decoration:none" href="">Bug ID</a></th>
    <th><a style="text-decoration:none" href="">Category</a></th>
    <th><a style="text-decoration:none" href="">Summary</a></th>
    <th><a style="text-decoration:none" href="">Severity</a></th>
    <th><a style="text-decoration:none" href="">Created On</a></th>
    <th><a style="text-decoration:none" href="">Status</a></th>
    {% for bug in recent_bug_reports %}
    <tr>
    <td><a style="text-decoration:none" href="{% url 'main:detail' bug.id %}">{{ bug.id }}</a></td>
    <td><a style="text-decoration:none" href="{% url 'main:detail' bug.id %}">{{ bug.bug_category }}</a></td>
    <td><a style="text-decoration:none" href="{% url 'main:detail' bug.id %}">{{ bug.bug_summary }}</a></td>
    <td><a style="text-decoration:none" href="{% url 'main:detail' bug.id %}">{{ bug.bug_severity }}</a></td>
    <td><a style="text-decoration:none" href="{% url 'main:detail' bug.id %}">{{ bug.date_reported }}</a></td>
    <td><a style="text-decoration:none" href="{% url 'main:detail' bug.id %}">{{ bug.bug_status }}</a></td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>No Bugs were reported yet</p>
{% endif %}

main/templates/main/login.html
<!--
<!DOCTYPE html>

<html>

    <head>
    </head>

    <body>
        <input type="text" name="Username", placeholder="Username"><br \>
        <input type="password" name="Password", placeholder="Password"><br \>
        <input type="checkbox"> Remember me<br \>
        <a href=""><button>Login</button></a><br \>
        Don't have an account? <a href="{% url 'main:register'%}"><button>Register</button></a>
    </body>

</html> -->

<form action="" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Submit">
</form><br \>
Dont have an account? <a href="{% url 'main:register' %}"><button>Register</button></a>

main/templates/main/pass_no_match.html
<h1>Passwords Dont Match. Try Again</h1>
<a href="{% url 'main:register' %}"><button>Register Again</button></a>

main/templates/main/register.html
<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Submit">
</form><br \>
Already have an account? <a href="{% url 'main:login' %}"><button>Login</button></a>

main/templates/main/register_prev.html
<!DOCTYPE html>

<html>

    <head>
    </head>

    <body>
        <input type="text" name="first_name" placeholder="First Name"><br \>
        <input type="text" name="last_name" placeholder="Last Name"><br \>
        <input type="text" name="Username", placeholder="Username"><br \>
        <input type="password" name="Password", placeholder="Password"><br \>
        <input type="password" name="Password", placeholder="Confirm Password"><br \>
        <input type="email" name="Email", placeholder="Email"><br \>
        <input type="radio"> Agree to the Terms and Conditions<br \>
        <input type="checkbox"> Remember me<br \>
        <a href=""><button>Sign Up</button></a><br \>
        Have an Account? <a href="{% url 'main:login' %}"><button>Login</button></a><br \>
    </body>

</html>

main/templates/main/user_bug_creation.html
<form action="" method = "post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Submit">
</form>

main/templates/main/user_bug_creation_temp.html

<!--
Summary: <br \>
<textarea name="summary" placeholder="Summary of the bug" cols="80"></textarea><br \><br \><br \>
Description:<br \><br \>
<textarea name="description" placeholder="Enter the Description of the bug" rows="20" cols="80"></textarea><br \><br \><br \>
Category: <input type="text" name="Category" placeholder="Category"><br \><br \><br \>
Severity: <select name="severity">
    <option value="severity">Low</option>
    <option value="severity">Medium</option>
    <option value="severity">High</option>
    <option value="severity">Critical</option>
</select><br \><br \><br \>

<a href=""><button>Submit</button></a> -->

<form action="" method = "post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Submit">
</form>

main/templates/main/welcome.html
<h1>Welcome {{user}}</h1>